### ISSUE TITLE
Does not work with recent pybtex==0.18

### ISSUE THREAD

**Issue by jluttine** [mcmtroffaes/sphinxcontrib-bibtex#68]
With pybtex==0.17, sphinxcontrib-bibtex has been working but with the recent pybtex==0.18 it does not anymore. Tried with both Python 3.3 and 3.4.

When building the docs, it stops with error:

```
Exception occurred:
  File "/home/jluttine/TMP/lib/python3.4/site-packages/pybtex/database/__init__.py", line 287, in __init__
    self.type = type_.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
The full traceback has been saved in /tmp/sphinx-err-8en18iiv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

The contents of the log file:

```
# Sphinx version: 1.2.2
# Python version: 3.4.0
# Docutils version: 0.11 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   sphinx.ext.oldcmarkup from /home/jluttine/TMP/lib/python3.4/site-packages/sphinx/ext/oldcmarkup.py
#   sphinxcontrib.bibtex from /home/jluttine/TMP/lib/python3.4/site-packages/sphinxcontrib/bibtex/__init__.py
Traceback (most recent call last):
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/environment.py", line 477, in update_generator
    self.read_doc(docname, app=app)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/environment.py", line 624, in read_doc
    pub.publish()
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2661, in blank
    context, self.state_machine.abs_line_number() - 1)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 418, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
    return self.inliner.parse(text, lineno, self.memo, self.parent)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 513, in parse
    lineno)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 776, in interpreted_or_phrase_ref
    lineno)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 856, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinx/roles.py", line 139, in __call__
    return self.result_nodes(inliner.document, env, refnode, is_ref=True)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinxcontrib/bibtex/roles.py", line 34, in result_nodes
    for key in keys]
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinxcontrib/bibtex/roles.py", line 34, in <listcomp>
    for key in keys]
  File "/home/jluttine/TMP/lib/python3.4/site-packages/sphinxcontrib/bibtex/roles.py", line 41, in _fake_entry
    entry = pybtex.database.Entry(type_=None)
  File "/home/jluttine/TMP/lib/python3.4/site-packages/pybtex/database/__init__.py", line 287, in __init__
    self.type = type_.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```
